package com.du.dao;

import com.du.entry.LoseGoodsCopy;

public interface LoseGoodsCopyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_goods_copy
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    int deleteByPrimaryKey(String loseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_goods_copy
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    int insert(LoseGoodsCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_goods_copy
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    int insertSelective(LoseGoodsCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_goods_copy
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    LoseGoodsCopy selectByPrimaryKey(String loseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_goods_copy
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    int updateByPrimaryKeySelective(LoseGoodsCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_goods_copy
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    int updateByPrimaryKey(LoseGoodsCopy record);
}