package com.du.dao;

import com.du.entry.LoseGood;
import com.du.entry.LoserGood;
import org.apache.ibatis.annotations.Param;

import java.util.ArrayList;

public interface LoserGoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loser_goods
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    int deleteByPrimaryKey(Integer loserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loser_goods
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    int insert(LoserGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loser_goods
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    int insertSelective(LoserGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loser_goods
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    LoserGood selectByPrimaryKey(Integer loserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loser_goods
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    int updateByPrimaryKeySelective(LoserGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loser_goods
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(LoserGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loser_goods
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    int updateByPrimaryKey(LoserGood record);
    /*
* user页面自动查询拾主
* */
    ArrayList<LoserGood> selectAutoLoserGood(@Param(value="start")int start, @Param(value="end")int end);
    /*
   * 查询某个账号下的拾物个数
   * */
    ArrayList<LoserGood> selectAutoLoserGoodByNum(String num);
/*
* 查询所有的信息
* */
    ArrayList<LoserGood> selectAllLoser();
    /*搜索*/
    ArrayList<LoserGood> searchByKey(@Param(value = "key") String key,@Param(value = "type") String type,
                                    @Param(value = "time") String time,@Param(value = "local") String local);

    /*审核*/
    int checked(int id);
    /*查询未审核的信息*/
    ArrayList<LoserGood> select_check();
    /*查询已审核的信息*/
    ArrayList<LoserGood> select_checked();
}