package com.du.dao;

import com.du.entry.LoseGood;
import org.apache.ibatis.annotations.Param;
import org.springframework.context.annotation.Configuration;

import java.util.ArrayList;

@Configuration
public interface LoseGoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_goods
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    int deleteByPrimaryKey(Integer loseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_goods
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    int insert(LoseGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_goods
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    int insertSelective(LoseGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_goods
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    LoseGood selectByPrimaryKey(Integer loseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_goods
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    int updateByPrimaryKeySelective(LoseGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_goods
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(LoseGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_goods
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    int updateByPrimaryKey(LoseGood record);
    /*
    * 查询总数据的前几个
    * */
    ArrayList<LoseGood> selectAutoLoseGood(@Param(value="start")int start, @Param(value="end")int end);
    /*
    * 查询某个账号下的失物个数
    * */
    ArrayList<LoseGood> selectAutoLoseGoodByNum(String Student_num);

    ArrayList<LoseGood> selectAllLose();

    ArrayList<LoseGood> searchByKey(@Param(value = "key") String key,@Param(value = "type") String type,
                                    @Param(value = "time") String time,@Param(value = "local") String local);

}