package com.du.dao;

import com.du.entry.LoseGood;
import com.du.entry.LoserGood;
import com.du.entry.Losered;
import org.apache.ibatis.annotations.Param;

import java.util.ArrayList;

public interface LoseredMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losered
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    int deleteByPrimaryKey(Integer loseredId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losered
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    int insert(Losered record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losered
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    int insertSelective(Losered record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losered
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    Losered selectByPrimaryKey(Integer loseredId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losered
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    int updateByPrimaryKeySelective(Losered record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losered
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    int updateByPrimaryKey(Losered record);

}