package com.du.entry;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;

public class LoserGood {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loser_goods.loser_id
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private Integer loserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loser_goods.loser_name
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String loserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loser_goods.loser_img
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String loserImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loser_goods.loser_time
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private LocalDateTime loserTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loser_goods.loser_checked
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String loserChecked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loser_goods.loser_claim
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String loserClaim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loser_goods.student_num
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String studentNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loser_goods.loser_describe
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String loserDescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loser_goods.loser_id
     *
     * @return the value of loser_goods.loser_id
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String loserType;



    public Integer getLoserId() {
        return loserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loser_goods.loser_id
     *
     * @param loserId the value for loser_goods.loser_id
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoserId(Integer loserId) {
        this.loserId = loserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loser_goods.loser_name
     *
     * @return the value of loser_goods.loser_name
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getLoserName() {
        return loserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loser_goods.loser_name
     *
     * @param loserName the value for loser_goods.loser_name
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoserName(String loserName) {
        this.loserName = loserName == null ? null : loserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loser_goods.loser_img
     *
     * @return the value of loser_goods.loser_img
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getLoserImg() {
        return loserImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loser_goods.loser_img
     *
     * @param loserImg the value for loser_goods.loser_img
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoserImg(String loserImg) {
        this.loserImg = loserImg == null ? null : loserImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loser_goods.loser_time
     *
     * @return the value of loser_goods.loser_time
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getLoserTime() {

        DateTimeFormatter f = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        if(loserTime==null){
            return null;
        }else return  loserTime.format(f);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loser_goods.loser_time
     *
     * @param loserTime the value for loser_goods.loser_time
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoserTime(LocalDateTime loserTime) {
        this.loserTime = loserTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loser_goods.loser_checked
     *
     * @return the value of loser_goods.loser_checked
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getLoserChecked() {
        return loserChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loser_goods.loser_checked
     *
     * @param loserChecked the value for loser_goods.loser_checked
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoserChecked(String loserChecked) {
        this.loserChecked = loserChecked == null ? null : loserChecked.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loser_goods.loser_claim
     *
     * @return the value of loser_goods.loser_claim
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getLoserClaim() {
        return loserClaim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loser_goods.loser_claim
     *
     * @param loserClaim the value for loser_goods.loser_claim
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoserClaim(String loserClaim) {
        this.loserClaim = loserClaim == null ? null : loserClaim.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loser_goods.student_num
     *
     * @return the value of loser_goods.student_num
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getStudentNum() {
        return studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loser_goods.student_num
     *
     * @param studentNum the value for loser_goods.student_num
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setStudentNum(String studentNum) {
        this.studentNum = studentNum == null ? null : studentNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loser_goods.loser_describe
     *
     * @return the value of loser_goods.loser_describe
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getLoserDescribe() {
        return loserDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loser_goods.loser_describe
     *
     * @param loserDescribe the value for loser_goods.loser_describe
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoserDescribe(String loserDescribe) {
        this.loserDescribe = loserDescribe == null ? null : loserDescribe.trim();
    }

    public String getLoserType() {
        return loserType;
    }

    public void setLoserType(String loserType) {
        this.loserType = loserType;
    }
}