package com.du.entry;

import java.util.Date;

public class Losered {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losered.losered_id
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private Integer loseredId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losered.lose_id
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private Integer loseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losered.loser_id
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private Integer loserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losered.losered_time
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private Date loseredTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losered.losered_id
     *
     * @return the value of losered.losered_id
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public Integer getLoseredId() {
        return loseredId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losered.losered_id
     *
     * @param loseredId the value for losered.losered_id
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoseredId(Integer loseredId) {
        this.loseredId = loseredId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losered.lose_id
     *
     * @return the value of losered.lose_id
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public Integer getLoseId() {
        return loseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losered.lose_id
     *
     * @param loseId the value for losered.lose_id
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoseId(Integer loseId) {
        this.loseId = loseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losered.loser_id
     *
     * @return the value of losered.loser_id
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public Integer getLoserId() {
        return loserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losered.loser_id
     *
     * @param loserId the value for losered.loser_id
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoserId(Integer loserId) {
        this.loserId = loserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losered.losered_time
     *
     * @return the value of losered.losered_time
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public Date getLoseredTime() {
        return loseredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losered.losered_time
     *
     * @param loseredTime the value for losered.losered_time
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoseredTime(Date loseredTime) {
        this.loseredTime = loseredTime;
    }
}