package com.du.entry;

import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;

public class LoseGood {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_goods.lose_id
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private Integer loseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_goods.lose_name
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String loseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_goods.lose_description
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String loseDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_goods.lose_time
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private LocalDateTime loseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_goods.lose_checked
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String loseChecked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_goods.lose_claim
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String loseClaim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_goods.student_num
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String studentNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_goods.lose_img
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String loseImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_goods.lose_id
     *
     * @return the value of lose_goods.lose_id
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String loseType;



    public Integer getLoseId() {
        return loseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_goods.lose_id
     *
     * @param loseId the value for lose_goods.lose_id
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoseId(Integer loseId) {
        this.loseId = loseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_goods.lose_name
     *
     * @return the value of lose_goods.lose_name
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getLoseName() {
        return loseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_goods.lose_name
     *
     * @param loseName the value for lose_goods.lose_name
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoseName(String loseName) {
        this.loseName = loseName == null ? null : loseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_goods.lose_description
     *
     * @return the value of lose_goods.lose_description
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getLoseDescription() {
        return loseDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_goods.lose_description
     *
     * @param loseDescription the value for lose_goods.lose_description
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoseDescription(String loseDescription) {
        this.loseDescription = loseDescription == null ? null : loseDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_goods.lose_time
     *
     * @return the value of lose_goods.lose_time
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getLoseTime() {

        DateTimeFormatter f = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        if(loseTime==null){
            return null;
        }else return  loseTime.format(f);

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_goods.lose_time
     *
     * @param loseTime the value for lose_goods.lose_time
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoseTime(LocalDateTime loseTime) {


        this.loseTime = loseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_goods.lose_checked
     *
     * @return the value of lose_goods.lose_checked
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getLoseChecked() {
        return loseChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_goods.lose_checked
     *
     * @param loseChecked the value for lose_goods.lose_checked
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoseChecked(String loseChecked) {
        this.loseChecked = loseChecked == null ? null : loseChecked.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_goods.lose_claim
     *
     * @return the value of lose_goods.lose_claim
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getLoseClaim() {
        return loseClaim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_goods.lose_claim
     *
     * @param loseClaim the value for lose_goods.lose_claim
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoseClaim(String loseClaim) {
        this.loseClaim = loseClaim == null ? null : loseClaim.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_goods.student_num
     *
     * @return the value of lose_goods.student_num
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getStudentNum() {
        return studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_goods.student_num
     *
     * @param studentNum the value for lose_goods.student_num
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setStudentNum(String studentNum) {
        this.studentNum = studentNum == null ? null : studentNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_goods.lose_img
     *
     * @return the value of lose_goods.lose_img
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getLoseImg() {
        return loseImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_goods.lose_img
     *
     * @param loseImg the value for lose_goods.lose_img
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setLoseImg(String loseImg) {
        this.loseImg = loseImg;
    }

    public String getLoseType() {
        return loseType;
    }

    public void setLoseType(String loseType) {
        this.loseType = loseType;
    }
}