package com.du.entry;

import java.util.Date;

public class LoseGoodsCopy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_goods_copy.lose_id
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    private String loseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_goods_copy.lose_name
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    private String loseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_goods_copy.lose_description
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    private String loseDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_goods_copy.lose_img
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    private String loseImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_goods_copy.lose_time
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    private Date loseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_goods_copy.lose_checked
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    private String loseChecked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_goods_copy.lose_claim
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    private String loseClaim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_goods_copy.student_num
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    private String studentNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_goods_copy.lose_id
     *
     * @return the value of lose_goods_copy.lose_id
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    public String getLoseId() {
        return loseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_goods_copy.lose_id
     *
     * @param loseId the value for lose_goods_copy.lose_id
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    public void setLoseId(String loseId) {
        this.loseId = loseId == null ? null : loseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_goods_copy.lose_name
     *
     * @return the value of lose_goods_copy.lose_name
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    public String getLoseName() {
        return loseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_goods_copy.lose_name
     *
     * @param loseName the value for lose_goods_copy.lose_name
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    public void setLoseName(String loseName) {
        this.loseName = loseName == null ? null : loseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_goods_copy.lose_description
     *
     * @return the value of lose_goods_copy.lose_description
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    public String getLoseDescription() {
        return loseDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_goods_copy.lose_description
     *
     * @param loseDescription the value for lose_goods_copy.lose_description
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    public void setLoseDescription(String loseDescription) {
        this.loseDescription = loseDescription == null ? null : loseDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_goods_copy.lose_img
     *
     * @return the value of lose_goods_copy.lose_img
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    public String getLoseImg() {
        return loseImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_goods_copy.lose_img
     *
     * @param loseImg the value for lose_goods_copy.lose_img
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    public void setLoseImg(String loseImg) {
        this.loseImg = loseImg == null ? null : loseImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_goods_copy.lose_time
     *
     * @return the value of lose_goods_copy.lose_time
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    public Date getLoseTime() {
        return loseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_goods_copy.lose_time
     *
     * @param loseTime the value for lose_goods_copy.lose_time
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    public void setLoseTime(Date loseTime) {
        this.loseTime = loseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_goods_copy.lose_checked
     *
     * @return the value of lose_goods_copy.lose_checked
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    public String getLoseChecked() {
        return loseChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_goods_copy.lose_checked
     *
     * @param loseChecked the value for lose_goods_copy.lose_checked
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    public void setLoseChecked(String loseChecked) {
        this.loseChecked = loseChecked == null ? null : loseChecked.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_goods_copy.lose_claim
     *
     * @return the value of lose_goods_copy.lose_claim
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    public String getLoseClaim() {
        return loseClaim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_goods_copy.lose_claim
     *
     * @param loseClaim the value for lose_goods_copy.lose_claim
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    public void setLoseClaim(String loseClaim) {
        this.loseClaim = loseClaim == null ? null : loseClaim.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_goods_copy.student_num
     *
     * @return the value of lose_goods_copy.student_num
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    public String getStudentNum() {
        return studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_goods_copy.student_num
     *
     * @param studentNum the value for lose_goods_copy.student_num
     *
     * @mbggenerated Wed Dec 27 22:04:18 CST 2017
     */
    public void setStudentNum(String studentNum) {
        this.studentNum = studentNum == null ? null : studentNum.trim();
    }
}