package com.du.entry;

public class StudentUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_user.student_num
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String studentNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_user.user_name
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_user.password
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_user.grade
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_user.phone_num
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    private String phoneNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_user.student_num
     *
     * @return the value of school_user.student_num
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getStudentNum() {
        return studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_user.student_num
     *
     * @param studentNum the value for school_user.student_num
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setStudentNum(String studentNum) {
        this.studentNum = studentNum == null ? null : studentNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_user.user_name
     *
     * @return the value of school_user.user_name
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_user.user_name
     *
     * @param userName the value for school_user.user_name
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_user.password
     *
     * @return the value of school_user.password
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_user.password
     *
     * @param password the value for school_user.password
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_user.grade
     *
     * @return the value of school_user.grade
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_user.grade
     *
     * @param grade the value for school_user.grade
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_user.phone_num
     *
     * @return the value of school_user.phone_num
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_user.phone_num
     *
     * @param phoneNum the value for school_user.phone_num
     *
     * @mbggenerated Mon Dec 25 21:27:10 CST 2017
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }
}